#index:
#    path: /
#    controller: App\Controller\DefaultController::index

mailer:
  path: /mail
  controller: App\Controller\MailerController
  methods: [GET]

mailer_async:
  path: /mail-async
  controller: App\Controller\RegisterController
  methods: [GET]
